### ISSUE TITLE
Build with `ng build --prod --aot`

### ISSUE THREAD

**Issue by jftsaraiva** [CharlesElGriego/angular-aot-dynamic-components#4]
Hi,

I saw your comment in https://github.com/angular/angular/issues/15275#issuecomment-602746321 and tried this solution.

It worked well with `ng s --aot=true` but if I try with `ng build --prod --aot` and serve dist folder with `http-server` i'm getting:

```
ERROR Error: Uncaught (in promise): Error: Unexpected value 'class{}' imported by the module 'class{}'. Please add a @NgModule annotation.
```

You don't have this error?

Thanks.

**Comment by jftsaraiva** [comment]
I thought the issue was related to AOT but the problem is with `--prod`. Worked well with only `ng build --aot`

**Comment by CharlesElGriego** [comment]
I'm looking at this right now, sorry the delay

**Comment by CharlesElGriego** [comment]
@jftsaraiva fyi, it's not necessary to add --aot when it's in prod build. 
I also updated the app with a solution, as I understand buildOptimizer: true is removing the compiler

**Comment by CharlesElGriego** [comment]
Don't hesite to contact me if you have any questions... Also if you want to add an star to the project I'll appreciated it.
