### ISSUE TITLE
Latest angular compiler (ivy) allows for AoT production build, but running the code fails

### ISSUE THREAD

**Issue by Nixon-Joseph** [CharlesElGriego/angular-aot-dynamic-components#6]
Receiving the console error that matches here: https://github.com/angular/angular/issues/35788 when attempting to view the application after production build using this dynamic template method.

Looks like it's a compiler issue, and it may/may not be resolved. I couldn't figure out any way around it.

**Comment by CharlesElGriego** [comment]
Can you explain me how can I recreate this bug?

**Comment by Nixon-Joseph** [comment]
@CharlesElGriego creating a repro now

**Comment by Nixon-Joseph** [comment]
[repro.zip](https://github.com/CharlesElGriego/angular-aot-dynamic-components/files/4951025/repro.zip)
Attached is a reproduction - I've copied your service verbatim, and used it just how you did in your example.
ng build -> runs awesome just as expected
ng build --prod -> compiles great, but when you actually go to view the page, there is a JIT error:
```
main.efbc9c79b1915527b268.js:1 ERROR Error: Uncaught (in promise): Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
```
I've obviously tried following what it suggests, but without any luck.

npm version: 6.12.0
angular/cli version:
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.3
Node: 12.13.0
OS: win32 x64

Angular: 10.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.3
@angular-devkit/build-angular     0.1000.3
@angular-devkit/build-optimizer   0.1000.3
@angular-devkit/build-webpack     0.1000.3
@angular-devkit/core              10.0.3
@angular-devkit/schematics        10.0.3
@angular/cli                      10.0.3
@ngtools/webpack                  10.0.3
@schematics/angular               10.0.3
@schematics/update                0.1000.3
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
```

**Comment by CharlesElGriego** [comment]
I'm looking at this right now

**Comment by CharlesElGriego** [comment]
@Nixon-Joseph 
I updated the app with a solution, as I understand buildOptimizer: true is removing the compiler.
Don't hesite to contact me if you have any questions... Also if you want to add an star to the project I'll appreciated it.

**Comment by Nixon-Joseph** [comment]
Thanks for the update. I'd love a solution that could not disable the optimizer. There's jot really a difference in file size from non optimized and not aot.
I've run into similar issues in c#, and in that case we just have to trick the optimizer into understanding that we're definitely using the class. 

Although, I could totally see the Angular team removing that class specifically, because of what it is.

**Comment by Amolip** [comment]
If I use **ng build --prod --aot=true --buildOptimizer=true**  i am getting  Angular JIT compilation failed: '@angular/compiler' not loaded error on server 

but if I **use ng b --prod --aot=false --build-optimizer=false** command to create a disc folder it's working fine...
is there any other solution for this
